# Generated by Django 2.2.2 on 2019-06-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
