# Generated by Django 2.2.2 on 2019-06-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hits',
            field=models.BinaryField(blank=True, default=0, null=True),
        ),
    ]
