# Generated by Django 2.2.2 on 2019-06-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190625_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
