# Generated by Django 2.2.2 on 2019-06-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
