# Generated by Django 2.2.2 on 2019-06-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
