# Generated by Django 2.2.2 on 2019-06-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190626_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
