# Generated by Django 2.2.2 on 2019-06-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='index',
        ),
    ]
