# Generated by Django 2.2.2 on 2019-06-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_post_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
