# Generated by Django 2.2.2 on 2019-06-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190626_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=20)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_pw', models.CharField(blank=True, max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_post',
                'verbose_name_plural': 'posts_admin',
                'verbose_name': 'post_admin',
                'ordering': ('-id',),
            },
        ),
    ]
