# Generated by Django 2.2.2 on 2019-06-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190626_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, max_length=2)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('inter', models.CharField(blank=True, max_length=10)),
                ('dong', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'survey',
                'db_table': 'survey_data',
                'verbose_name_plural': 'surveys',
            },
        ),
    ]
