# Generated by Django 2.2.3 on 2019-07-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_uploadboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='result1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='result2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='result3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
