# Generated by Django 2.2.2 on 2019-07-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20190705_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadboard',
            old_name='title',
            new_name='file_title',
        ),
    ]
